coordinator:
  model_name: DeepSeek-V3
  model_provider: DeepSeek

planner:
  model_name: DeepSeek-V3
  model_provider: DeepSeek

auto_accepted_plan: false
max_plan_iterations: 1
max_step_num: 3
max_search_results: 3